### ISSUE TITLE
Fix "Stars"

### ISSUE THREAD

**Issue by carsonSgit** [tjklint/tjklint#1]
On your README.md, you have a "Stars" heading as such:

## Stars

Followed by GitHub Trophies. Resolve this.

**Comment by carsonSgit** [comment]
![image](https://github.com/tjklint/tjklint/assets/92652800/5987ca8d-6ad8-49ea-bdec-6232147e41cf)

As further reference

**Comment by tjklint** [comment]
Resolved. Closing issue.
